[theme]
primaryColor="#0077b6"          # Premium blue
backgroundColor="#f8f9fa"       # Light background
secondaryBackgroundColor="#ffffff"
textColor="#212529"             # Dark text for readability
font="sans serif"
